name: Build API

on:
  workflow_call:
    environment:
        description: "The environment to deploy to"
        required: true
        type: string
        
  jobs:
    build-api:
      name: Build API
      runs-on: ubuntu-latest
      environment:
        name: ${{ inputs.environment }}
      env:
        CI: true
        FORCE_COLOR: true
      defaults:
        run:
          shell: bash
          working-directory: ./api

      steps:
        - name: Check out the code
          uses: actions/checkout@v4

        - name: Setup
          uses: ./.github/actions/setup
          with:
            working_directory: ./api
        
        - name: Build API code
          run: |
            echo "Building API code ..."
            sh build.sh
        
        - name: Zip build output
          shell: bash
          run: |
            cd build
            zip -rq ../build.zip .
        
        - name: Upload build.zip as artifact
          uses: actions/upload-artifact@v4
          with:
            name: api-build.zip
            path: ./api/build.zip
