name: _build_api
description: |
  This workflow builds the API code and uploads the build output as an artifact.
  It is designed to be reusable and can be called from other workflows.
  The workflow is triggered by a workflow call, which means it can be invoked from other workflows.

on:
  workflow_call:
    inputs:
      environment:
          description: "The environment to deploy to"
          required: true
          type: string
        
jobs:
  
  build-api:
    name: Build API
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    env:
      CI: true
      FORCE_COLOR: true
    defaults:
      run:
        shell: bash
        working-directory: ./api

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          working_directory: ./api
      
      - name: Build API code
        run: |
          echo "Building API code ..."
          sh build.sh
      
      - name: Zip build output
        shell: bash
        run: |
          cd build
          zip -rq ../build.zip .
      
      - name: Upload build.zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-build
          path: ./api/build.zip
