name: _deploy
description: This workflow deploys the API to the specified environment.
  It is designed to be reusable and can be called from other workflows.
  The workflow is triggered by a workflow call, which means it can be invoked from other workflows.

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
      api_function_arn:
        description: 'The ARN of the API function'
        required: true
        type: string
      app_deployment_bucket_arn:
        description: 'The ARN of the deployment bucket'
        required: true
        type: string
      app_cloudfront_id:
        description: 'The CloudFront ID for the app'
        required: true
        type: string
    secrets:
      google_captcha_secret_key:
        description: 'Google reCAPTCHA secret key'
        required: true
      deployment_github_token:
        description: 'GitHub token for deployment'
        required: true

jobs:
  deploy-api:
    name: Deploy API
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    env:
      CI: true
      FORCE_COLOR: true
    permissions:
      id-token: write
    defaults:
      run:
        shell: bash

    steps:
      - name: Download API build artifact
        uses: actions/download-artifact@v4
        with:
          name: api-build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_OIDC_DEPLOYMENT_ROLE_ARN }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Deploy backend services
        env:
          API_FUNCTION_ARN: ${{ inputs.api_function_arn }}
          APP_NAME: ${{ vars.APP_NAME }}
          GOOGLE_CAPTCHA_SECRET_KEY: ${{ secrets.google_captcha_secret_key }}
          ALLOWED_ORIGINS: https://go.${{ vars.ROOT_DOMAIN }}
        run: |
          echo "Deploying API ..."
          sh deploy.sh

  deploy-web:
    name: Deploy Web
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    permissions:
      contents: write
      id-token: write
      pages: write
    env:
      CI: true
      FORCE_COLOR: true
    defaults:
      run:
        shell: bash

    steps:
      - name: Download Web build artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build

      - name: List files
        run: |
          echo "Listing files in the current directory..."
          ls -al

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_OIDC_DEPLOYMENT_ROLE_ARN }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Deploy frontend services
        env:
          APP_DEPLOYMENT_BUCKET_ARN: ${{ inputs.app_deployment_bucket_arn }}
          APP_CLOUDFRONT_ID: ${{ inputs.app_cloudfront_id }}
        run: |
          echo "Deploying Web app ..."
          sh deploy.sh
