name: _deploy
description: This workflow deploys the API to the specified environment.
  It is designed to be reusable and can be called from other workflows.
  The workflow is triggered by a workflow call, which means it can be invoked from other workflows.

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
      api_function_arn:
        description: 'The ARN of the API function'
        required: true
        type: string

jobs:

  deploy-api:
    name: Deploy API
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    env:
      CI: true
      FORCE_COLOR: true
    permissions:
      id-token: write
    defaults:
      run:
        shell: bash

    steps:
      - name: Download API build artifact
        uses: actions/download-artifact@v4
        with:
          name: api-build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_OIDC_DEPLOYMENT_ROLE_ARN }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Update backend services
        run: |
          echo "Updating backend services..."
          echo "Function is available at ${{ inputs.api_function_arn }}"
          zip -rq build.zip ./*
          aws lambda update-function-code --function-name ${{ inputs.api_function_arn }} --zip-file fileb://build.zip
  
  deploy-web:
    name: Deploy Web
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    permissions:
      id-token: write
      pages: write
    env:
      CI: true
      FORCE_COLOR: true
    defaults:
      run:
        shell: bash
    
    steps:
      - name: Download Web build artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build
      
      - name: List files
        run: |
          echo "Listing files in the current directory..."
          ls -al

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: web-build