name: _deploy
description: This workflow deploys the API to the specified environment.
  It is designed to be reusable and can be called from other workflows.
  The workflow is triggered by a workflow call, which means it can be invoked from other workflows.

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
      api_function_arn:
        description: 'The ARN of the API function'
        required: true
        type: string
      aws_role_to_assume:
        description: 'The ARN of the AWS OIDC deployment role'
        required: true
        type: string
      aws_default_region:
        description: 'The default AWS region'
        required: true
        type: string
      app_name:
        description: 'The name of the application'
        required: true
        type: string
    secrets:
      google_captcha_secret_key:
        description: 'Google reCAPTCHA secret key'
        required: true

jobs:
  deploy-api:
    name: Deploy API
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    env:
      CI: true
      FORCE_COLOR: true
    permissions:
      id-token: write
    defaults:
      run:
        shell: bash

    steps:
      - name: Download API build artifact
        uses: actions/download-artifact@v4
        with:
          name: api-build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws_role_to_assume }}
          aws-region: ${{ inputs.aws_default_region }}

      - name: Deploy backend services
        env:
          API_FUNCTION_ARN: ${{ inputs.api_function_arn }}
          APP_NAME: ${{ inputs.app_name }}
          GOOGLE_CAPTCHA_SECRET_KEY: ${{ secrets.google_captcha_secret_key }}
        run: |
          echo "Deploying API code ..."
          sh deploy.sh

  deploy-web:
    name: Deploy Web
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    permissions:
      contents: write
      id-token: write
      pages: write
    env:
      CI: true
      FORCE_COLOR: true
    defaults:
      run:
        shell: bash

    steps:
      - name: Download Web build artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build

      - name: List files
        run: |
          echo "Listing files in the current directory..."
          ls -al

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          keep_files: true
