name: _infra
description: |
  This workflow deploys the backend infrastructure using AWS CDK.
  It is designed to be reusable and can be called from other workflows.
  The workflow is triggered by a workflow call, which means it can be invoked from other workflows.

on:
  workflow_call:
    inputs:
      cdk_command:
        description: 'The CDK command to execute'
        required: true
        type: string
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
      aws_role_to_assume:
        description: 'The ARN of the AWS OIDC deployment role'
        required: true
        type: string
      aws_default_region:
        description: 'The default AWS region'
        required: true
        type: string
      app_name:
        description: 'The name of the application'
        required: true
        type: string
      aws_account_id:
        description: 'The AWS account ID'
        required: true
        type: string
    outputs:
      api_function_arn:
        description: 'The ARN of the API function'
        value: ${{ jobs.infra-cdk.outputs.api_function_arn }}

jobs:
  infra-cdk:
    name: CDK ${{ inputs.cdk_command }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    env:
      CI: true
      FORCE_COLOR: true
    permissions:
      id-token: write
    defaults:
      run:
        shell: bash
        working-directory: ./infra
    outputs:
      api_function_arn: ${{ steps.read-cdk-output.outputs.api_function_arn }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          working_directory: ./infra

      - name: Run CDK command ${{ inputs.cdk_command }}
        uses: ./.github/actions/cdk
        with:
          working_directory: ./infra
          command: ${{ inputs.cdk_command }}
          aws_account_id: ${{ inputs.aws_account_id }}
          aws_role_to_assume: ${{ inputs.aws_role_to_assume }}
          aws_default_region: ${{ inputs.aws_default_region }}
          app_name: ${{ inputs.app_name }}

      - name: Read CDK output
        if: ${{ inputs.cdk_command == 'deploy' }}
        id: read-cdk-output
        run: |
          echo "### 🚀 Infra deployment completed" >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          jq . cdk-outputs.json >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          API_FUNCTION_ARN=$(jq -r '.[].${{ inputs.app_name }}ApiFunctionOut' cdk-outputs.json)
          echo "$API_FUNCTION_ARN"
          echo "api_function_arn=$API_FUNCTION_ARN" >> "$GITHUB_OUTPUT"
