name: _infra
description: |
  This workflow deploys the backend infrastructure using AWS CDK.
  It is designed to be reusable and can be called from other workflows.
  The workflow is triggered by a workflow call, which means it can be invoked from other workflows.

on:
  workflow_call:
    inputs:
      cdk_command:
        description: 'The CDK command to execute'
        required: true
        type: string
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
    outputs:
      api_function_arn:
        description: 'The ARN of the API function'
        value: ${{ jobs.infra-cdk.outputs.api_function_arn }}
      api_domain:
        description: 'The domain of the API'
        value: ${{ jobs.infra-cdk.outputs.api_domain }}
      app_deployment_bucket_arn:
        description: 'The ARN of the deployment bucket'
        value: ${{ jobs.infra-cdk.outputs.app_deployment_bucket_arn }}
      app_cloudfront_id:
        description: 'The CloudFront ID for the app'
        value: ${{ jobs.infra-cdk.outputs.app_cloudfront_id }}

jobs:
  infra-cdk:
    name: CDK ${{ inputs.cdk_command }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    env:
      CI: true
      FORCE_COLOR: true
    permissions:
      id-token: write
    defaults:
      run:
        shell: bash
        working-directory: ./infra
    outputs:
      api_function_arn: ${{ steps.read-cdk-output.outputs.api_function_arn }}
      api_domain: ${{ steps.read-cdk-output.outputs.api_domain }}
      app_deployment_bucket_arn: ${{ steps.read-cdk-output.outputs.app_deployment_bucket_arn }}
      app_cloudfront_id: ${{ steps.read-cdk-output.outputs.app_cloudfront_id }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          working_directory: ./infra

      - name: Run CDK command ${{ inputs.cdk_command }}
        uses: ./.github/actions/cdk
        with:
          working_directory: ./infra
          command: ${{ inputs.cdk_command }}
          aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
          aws_role_to_assume: ${{ vars.AWS_GITHUB_OIDC_DEPLOYMENT_ROLE_ARN }}
          aws_default_region: ${{ vars.AWS_DEFAULT_REGION }}
          app_name: ${{ vars.APP_NAME }}
          root_domain: ${{ vars.ROOT_DOMAIN }}
          aws_hosted_zone_id: ${{ vars.AWS_HOSTED_ZONE_ID }}

      - name: Read CDK output
        if: ${{ inputs.cdk_command == 'deploy' }}
        id: read-cdk-output
        run: |
          echo "### 🚀 Infra deployment completed" >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          jq . cdk-outputs.json >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          API_FUNCTION_ARN=$(jq -r '.${{ vars.APP_NAME }}BackendStack.${{ vars.APP_NAME }}ApiFunctionOut' cdk-outputs.json)
          echo "api_function_arn=$API_FUNCTION_ARN" >> "$GITHUB_OUTPUT"
          API_DOMAIN=$(jq -r '.${{ vars.APP_NAME }}BackendStack.${{ vars.APP_NAME }}ApiDomainOut' cdk-outputs.json)
          echo "api_domain=$API_DOMAIN" >> "$GITHUB_OUTPUT"
          APP_DEPLOYMENT_BUCKET_ARN=$(jq -r '.${{ vars.APP_NAME }}BackendStack.${{ vars.APP_NAME }}AppDeploymentBucketOut' cdk-outputs.json)
          echo "app_deployment_bucket_arn=$APP_DEPLOYMENT_BUCKET_ARN" >> "$GITHUB_OUTPUT"
          APP_CLOUDFRONT_ID=$(jq -r '.${{ vars.APP_NAME }}FrontendStack.${{ vars.APP_NAME }}AppCloudfrontDistributionIdOut' cdk-outputs.json)
          echo "app_cloudfront_id=$APP_CLOUDFRONT_ID" >> "$GITHUB_OUTPUT"
