name: PROD Deploy

on:
  push:
    branches:
      - release/*
      - main
    tags:
      - 'v*'

jobs:
  diff-backend-infrastructure:
    name: Diff backend infrastructure
    uses: ./.github/workflows/_infra.yml
    with:
      cdk_command: diff
      environment: PROD
      aws_role_to_assume: ${{ vars.AWS_GITHUB_OIDC_DEPLOYMENT_ROLE_ARN }}
      aws_default_region: ${{ vars.AWS_DEFAULT_REGION }}
      app_name: ${{ vars.APP_NAME }}
      aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}

  deploy-backend-infrastructure:
    name: Deploy backend infrastructure
    needs: diff-backend-infrastructure
    uses: ./.github/workflows/_infra.yml
    with:
      cdk_command: deploy
      environment: PROD
      aws_role_to_assume: ${{ vars.AWS_GITHUB_OIDC_DEPLOYMENT_ROLE_ARN }}
      aws_default_region: ${{ vars.AWS_DEFAULT_REGION }}
      app_name: ${{ vars.APP_NAME }}
      aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}

  build:
    name: Build
    uses: ./.github/workflows/_build.yml
    with:
      environment: PROD

  deploy:
    name: Deploy
    needs: [deploy-backend-infrastructure, build]
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: PROD
      app_name: ${{ vars.APP_NAME }}
      aws_role_to_assume: ${{ vars.AWS_GITHUB_OIDC_DEPLOYMENT_ROLE_ARN }}
      aws_default_region: ${{ vars.AWS_DEFAULT_REGION }}
      api_function_arn: ${{ needs.deploy-backend-infrastructure.outputs.api_function_arn }}
    secrets:
      google_captcha_secret_key: ${{ secrets.google_captcha_secret_key }}
