name: Sandbox Deploy

on:
  push:
    branches:
      - develop

jobs:
  diff-backend-infrastructure:
    name: Diff backend infrastructure
    uses: ./.github/workflows/_infra.yml
    with:
      cdk_command: diff
      environment: sandbox

  deploy-backend-infrastructure:
    name: Deploy backend infrastructure
    needs: diff-backend-infrastructure
    uses: ./.github/workflows/_infra.yml
    with:
      cdk_command: deploy
      environment: sandbox

  build:
    name: Build
    uses: ./.github/workflows/_build.yml
    with:
      environment: sandbox

  deploy:
    name: Deploy
    needs: [deploy-backend-infrastructure, build]
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: sandbox
      api_function_arn: ${{ needs.deploy-backend-infrastructure.outputs.api_function_arn }}
