name: Sandbox Deploy

on:
  push:
    branches:
      - develop

jobs:

  diff-backend-infrastructure:
    name: Diff backend infrastructure
    uses: ./.github/workflows/_infra.yml
    with:
      cdk_command: diff
      environment: sandbox

  deploy-backend-infrastructure:
    name: Deploy backend infrastructure
    needs: diff-backend-infrastructure
    uses: ./.github/workflows/_infra.yml
    with:
      cdk_command: deploy
      environment: sandbox

  build-api:
    name: Build API
    uses: ./.github/workflows/_build_api.yml
  
  deploy-api:
    name: Deploy API
    needs: [deploy-backend-infrastructure, build-api]
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: sandbox

