name: Sandbox Deploy

on:
  push:
    branches:
      - develop

jobs:

  diff-backend-infrastructure:
    name: Diff backend infrastructure
    runs-on: ubuntu-latest
    environment:
      name: sandbox
    env:
      CI: true
      FORCE_COLOR: true
    permissions:
      id-token: write
    defaults:
      run:
        shell: bash
        working-directory: ./infra

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          aws_role_to_assume: ${{ vars.AWS_GITHUB_OIDC_DEPLOYMENT_ROLE_ARN }}
          aws_default_region: ${{ vars.AWS_DEFAULT_REGION }}
          working_directory: ./infra
      
      - name: Deployment
        uses: ./.github/actions/cdk
        with:
          aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
          aws_default_region: ${{ vars.AWS_DEFAULT_REGION }}
          working_directory: ./infra
          command: diff

  deploy-backend-infrastructure:
    name: Deploy backend infrastructure
    needs: diff-backend-infrastructure
    runs-on: ubuntu-latest
    environment:
      name: sandbox
    env:
      CI: true
      FORCE_COLOR: true
    permissions:
      id-token: write
    defaults:
      run:
        shell: bash
        working-directory: ./infra

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          aws_role_to_assume: ${{ vars.AWS_GITHUB_OIDC_DEPLOYMENT_ROLE_ARN }}
          aws_default_region: ${{ vars.AWS_DEFAULT_REGION }}
          working_directory: ./infra
      
      - name: Deployment
        uses: ./.github/actions/cdk
        with:
          aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
          aws_default_region: ${{ vars.AWS_DEFAULT_REGION }}
          working_directory: ./infra
          command: deploy
