name: Sandbox Deploy

on:
  push:
    branches:
      - develop

jobs:
  guardian:
    name: Guardian
    uses: ./.github/workflows/_guardian.yml
    with:
      environment: sandbox

  diff-backend-infrastructure:
    name: Diff backend infrastructure
    needs: guardian
    uses: ./.github/workflows/_infra.yml
    with:
      cdk_command: diff
      environment: sandbox

  deploy-backend-infrastructure:
    name: Deploy backend infrastructure
    needs: diff-backend-infrastructure
    uses: ./.github/workflows/_infra.yml
    with:
      cdk_command: deploy
      environment: sandbox

  build:
    name: Build
    needs: guardian
    uses: ./.github/workflows/_build.yml
    with:
      environment: sandbox

  deploy:
    name: Deploy
    needs: [deploy-backend-infrastructure, build]
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: sandbox
      api_function_arn: ${{ needs.deploy-backend-infrastructure.outputs.api_function_arn }}
      deployment_github_repo: ${{ vars.DEPLOYMENT_GITHUB_REPO }}
    secrets:
      google_captcha_secret_key: ${{ secrets.GOOGLE_CAPTCHA_SECRET_KEY }}
      deployment_github_token: ${{ secrets.DEPLOYMENT_GITHUB_TOKEN }}
