name: Sandbox Deploy

on:
  push:
    branches:
      - develop

jobs:

  build-api:
    name: Build API
    uses: ./.github/workflows/_api.yml
    with:
      environment: sandbox

  diff-backend-infrastructure:
    name: Diff backend infrastructure
    uses: ./.github/workflows/_infra.yml
    with:
      cdk_command: diff
      environment: sandbox

  deploy-backend-infrastructure:
    name: Deploy backend infrastructure
    needs: diff-backend-infrastructure
    uses: ./.github/workflows/_infra.yml
    with:
      cdk_command: deploy
      environment: sandbox
