name: Sandbox Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy-backend-infrastructure:
    name: Deploy backend infrastructure
    runs-on: ubuntu-latest
    environment:
      name: sandbox
    env:
      CI: true
      FORCE_COLOR: true
    defaults:
      run:
        shell: bash
        working-directory: ./infra

    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      
      - name: Print environment variables for debugging
        run: |
          echo "AWS_DEFAULT_REGION=${{ vars.AWS_DEFAULT_REGION }}"
          echo "AWS_GITHUB_OIDC_DEPLOYMENT_ROLE_ARN=${{ vars.AWS_GITHUB_OIDC_DEPLOYMENT_ROLE_ARN }}"
          echo "AWS_ACCOUNT_ID=${{ vars.AWS_ACCOUNT_ID }}"
        shell: bash

      - name: Setup
        uses: ./.github/actions/setup
        with:
          aws_role_to_assume: ${{ vars.AWS_GITHUB_OIDC_DEPLOYMENT_ROLE_ARN }}
          aws_default_region: ${{ vars.AWS_DEFAULT_REGION }}
      
      - name: Deployment
        uses: ./.github/actions/deploy
        with:
          aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
          aws_default_region: ${{ vars.AWS_DEFAULT_REGION }}
