name: Sandbox Deploy

on:
  push:
    branches:
      - develop

jobs:

  build-api:
    name: Build API
    uses: ./.github/workflows/_api.yml
    with:
      environment: sandbox

  diff-backend-infrastructure:
    name: Diff backend infrastructure
    uses: ./.github/workflows/_infra.yml
    with:
      cdk_command: diff
      environment: sandbox

  deploy-backend-infrastructure:
    name: Deploy backend infrastructure
    needs: diff-backend-infrastructure
    uses: ./.github/workflows/_infra.yml
    with:
      cdk_command: deploy
      environment: sandbox
  
  update-backend-services:
    name: Update backend services
    needs: [deploy-backend-infrastructure, build-api]
    runs-on: ubuntu-latest
    environment:
      name: sandbox
    env:
      CI: true
      FORCE_COLOR: true
    permissions:
      id-token: write
    defaults:
      run:
        shell: bash
    
    steps:

      - name: Download API build artifact
        uses: actions/download-artifact@v4
        with:
          name: api-build
          path: ./api-build.zip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_OIDC_DEPLOYMENT_ROLE_ARN }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Update backend services
        run: |
          ls -all
          echo "Updating backend services..."
          echo "Function is available at ${{ needs.deploy-backend-infrastructure.outputs.api_function_arn }}"
          aws lambda update-function-code --function-name ${{ needs.deploy-backend-infrastructure.outputs.api_function_arn }} --zip-file fileb://api-build.zip
