name: Sandbox Deploy

on:
  push:
    branches:
      - develop

jobs:

  build-api:
    name: Build API
    uses: ./.github/workflows/_api.yml
    with:
      environment: sandbox

  diff-backend-infrastructure:
    name: Diff backend infrastructure
    uses: ./.github/workflows/_infra.yml
    with:
      cdk_command: diff
      environment: sandbox

  deploy-backend-infrastructure:
    name: Deploy backend infrastructure
    needs: diff-backend-infrastructure
    uses: ./.github/workflows/_infra.yml
    with:
      cdk_command: deploy
      environment: sandbox
  
  update-backend-services:
    name: Update backend services
    needs: [deploy-backend-infrastructure, build-api]
    runs-on: ubuntu-latest
    
    steps:

      - name: Update backend services
        run: |
          echo "Updating backend services..."
          echo "Function is available at ${{ needs.deploy-backend-infrastructure.outputs.api_function_arn }}"
          # Add your update commands here
          # For example, you can use AWS CLI or any other tool to update your services
          # aws lambda update-function-code --function-name my-function --zip-file fileb://my-function.zip
